# Generated by Django 5.0 on 2024-03-18 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HFH_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='calories',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
