# Generated by Django 5.0 on 2024-03-20 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HFH_app', '0005_alter_food_calories'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodInMeal',
            fields=[
                ('food_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='HFH_app.food')),
                ('servings', models.IntegerField(default=1)),
            ],
            bases=('HFH_app.food',),
        ),
    ]
