# Generated by Django 5.0 on 2024-03-20 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HFH_app', '0006_foodinmeal'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodsEaten',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foodsEaten', models.ManyToManyField(to='HFH_app.food')),
            ],
        ),
        migrations.DeleteModel(
            name='FoodInMeal',
        ),
    ]
