# Generated by Django 5.0 on 2024-03-20 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HFH_app', '0007_foodseaten_delete_foodinmeal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='foodseaten',
            old_name='foodsEaten',
            new_name='foodEaten',
        ),
    ]
