# Generated by Django 5.0 on 2024-03-22 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HFH_app', '0009_rename_foodseaten_foodseatenlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodseatenlist',
            name='title',
            field=models.CharField(default='Test_List', max_length=100),
        ),
    ]
