# Generated by Django 5.0 on 2024-03-22 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HFH_app', '0010_foodseatenlist_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='foodGroups',
            field=models.CharField(choices=[('Baked Foods', 'Baked Foods'), ('Snacks', 'Snacks'), ('Sweets', 'Sweets'), ('Vegetables', 'Vegetables'), ('American Indian', 'American Indian'), ('Restaurant Foods', 'Restaurant Foods'), ('Beverages', 'Beverages'), ('Fats and Oils', 'Fats and Oils'), ('Meats', 'Meats'), ('Dairy and Egg Products', 'Dairy and Egg Products'), ('Baby Foods', 'Baby Foods'), ('Breakfast Cereals', 'Breakfast Cereals'), ('Soups and Sauces', 'Soups and Sauces'), ('Beans and Lentils', 'Beans and Lentils'), ('Fish', 'Fish'), ('Fruits', 'Fruits')], default='Baked Foods', max_length=50),
        ),
    ]
